CREATE TABLE DECIMAL_50_0 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 0)
);
CREATE TABLE DECIMAL_50_1 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 1)
);
CREATE TABLE DECIMAL_50_2 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 2)
);
CREATE TABLE DECIMAL_50_3 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 3)
);
CREATE TABLE DECIMAL_50_4 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 4)
);
CREATE TABLE DECIMAL_50_5 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 5)
);
CREATE TABLE DECIMAL_50_6 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 6)
);
CREATE TABLE DECIMAL_50_7 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 7)
);
CREATE TABLE DECIMAL_50_8 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 8)
);
CREATE TABLE DECIMAL_50_9 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 9)
);
CREATE TABLE DECIMAL_50_10 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 10)
);
CREATE TABLE DECIMAL_50_11 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 11)
);
CREATE TABLE DECIMAL_50_12 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 12)
);
CREATE TABLE DECIMAL_50_13 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 13)
);
CREATE TABLE DECIMAL_50_14 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 14)
);
CREATE TABLE DECIMAL_50_15 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 15)
);
CREATE TABLE DECIMAL_50_16 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 16)
);
CREATE TABLE DECIMAL_50_17 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 17)
);
CREATE TABLE DECIMAL_50_18 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 18)
);
CREATE TABLE DECIMAL_50_19 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 19)
);
CREATE TABLE DECIMAL_50_20 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 20)
);
CREATE TABLE DECIMAL_50_21 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 21)
);
CREATE TABLE DECIMAL_50_22 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 22)
);
CREATE TABLE DECIMAL_50_23 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 23)
);
CREATE TABLE DECIMAL_50_24 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 24)
);
CREATE TABLE DECIMAL_50_25 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 25)
);
CREATE TABLE DECIMAL_50_26 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 26)
);
CREATE TABLE DECIMAL_50_27 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 27)
);
CREATE TABLE DECIMAL_50_28 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 28)
);
CREATE TABLE DECIMAL_50_29 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 29)
);
CREATE TABLE DECIMAL_50_30 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 30)
);
CREATE TABLE DECIMAL_50_31 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 31)
);
CREATE TABLE DECIMAL_50_32 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 32)
);
CREATE TABLE DECIMAL_50_33 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 33)
);
CREATE TABLE DECIMAL_50_34 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 34)
);
CREATE TABLE DECIMAL_50_35 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 35)
);
CREATE TABLE DECIMAL_50_36 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 36)
);
CREATE TABLE DECIMAL_50_37 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 37)
);
CREATE TABLE DECIMAL_50_38 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 38)
);
CREATE TABLE DECIMAL_50_39 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 39)
);
CREATE TABLE DECIMAL_50_40 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 40)
);
CREATE TABLE DECIMAL_50_41 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 41)
);
CREATE TABLE DECIMAL_50_42 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 42)
);
CREATE TABLE DECIMAL_50_43 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 43)
);
CREATE TABLE DECIMAL_50_44 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 44)
);
CREATE TABLE DECIMAL_50_45 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 45)
);
CREATE TABLE DECIMAL_50_46 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 46)
);
CREATE TABLE DECIMAL_50_47 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 47)
);
CREATE TABLE DECIMAL_50_48 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 48)
);
CREATE TABLE DECIMAL_50_49 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 49)
);
CREATE TABLE DECIMAL_50_50 (
  ID    BIGSERIAL PRIMARY KEY,
  VALUE DECIMAL(50, 50)
);