CREATE TABLE timestamp_table (
  ID    BIGSERIAL PRIMARY KEY NOT NULL,
  value TIMESTAMP
);

CREATE TABLE timestamp_wtz_table (
  ID    BIGSERIAL PRIMARY KEY NOT NULL,
  value TIMESTAMP WITH TIME ZONE
);

CREATE TABLE timestamp_wotz_table (
  ID    BIGSERIAL PRIMARY KEY NOT NULL,
  value TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE date_table (
  ID    BIGSERIAL PRIMARY KEY NOT NULL,
  value DATE
);

CREATE TABLE time_table (
  ID    BIGSERIAL PRIMARY KEY NOT NULL,
  value TIME
);

CREATE TABLE time_wtz_table (
  ID    BIGSERIAL PRIMARY KEY NOT NULL,
  value TIME WITH TIME ZONE
);

CREATE TABLE time_wotz_table (
  ID    BIGSERIAL PRIMARY KEY NOT NULL,
  value TIME WITHOUT TIME ZONE
);

CREATE TABLE interval_table (
  ID    BIGSERIAL PRIMARY KEY NOT NULL,
  value INTERVAL
);